name: Test
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        java: [8-jdk, 11-jdk, 15-jdk]
    runs-on: ubuntu-20.04
    container:
      image: openjdk:${{ matrix.java }}
      options: --user root
    steps:
      - uses: actions/checkout@v1
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build test publishToMavenLocal --stacktrace
  buildNatives:
    strategy:
      matrix:
        target: [ x86_64, i686, aarch64 ]
    runs-on: windows-2019
    steps:
      # TODO: Fix macOS in future
      - uses: actions/checkout@v2
      - run: rustup target add ${{ matrix.target }}-pc-windows-msvc
      - name: Run Cargo
        run: cargo check --target ${{ matrix.target }}-pc-windows-msvc
        working-directory: ./native
